# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lognreg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lognreg',
            name='email',
            field=models.CharField(default='email@test.com', max_length=45),
            preserve_default=False,
        ),
    ]
